name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  linting:
    # Doesn't need to be checked in all OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.23"

      - name: Cache Deno dependencies
        uses: actions/cache@main
        env:
          cache-name: cache-deno-dependencies
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Check Code FMT
        run: deno fmt --check

      - name: Check Code Lint
        run: deno lint
